name: Test GameHub Pet Project

on:
  push:
    branches: [ main ]
  
  jobs:
    test:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
      
      - name: Start application
        run: |
          npx http-server -p 8080 &
          sleep 5
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
          wait-on: 'http://localhost:8080'